const lang = {
  zh: {
    nav: {
      brand: 'NOVARA',
      items: [
        { id: 'identity', label: '身份识别' },
        { id: 'equity', label: '股权机制' },
        { id: 'partner', label: '合作结构' },
        { id: 'incentive', label: '激励机制' },
      ],
      apply: '进入系统',
      darkMode: '切换到深色模式',
      lightMode: '切换到浅色模式',
      langToggle: 'EN',
    },
    hero: {
      badge: '全球未来能力排名与识别系统',
      title1: 'AI时代，真正稀缺的',
      title2: '不是能力，而是——',
      title3: '被系统识别、被世界承认的能力',
      desc: '我们在做一件事：建立全球未来能力排名与识别系统',
      btn: '进入系统',
      stats: [
        { num: 'Top 1%', label: '全球能力排名' },
        { num: '25–27%', label: '生态股权池' },
        { num: '5项', label: '核心价值体系' },
        { num: '长期', label: '能力资产积累' },
      ],
    },
    identity: {
      label: '身份识别',
      title1: '如果你是全球 Top 1%，',
      title2: '世界会知道吗',
      desc: '在这里——你是谁、你有多强、你做过什么，都会被记录',
      highlight: '不是你觉得你强，是系统证明你强',
      values: [
        { icon: '01', title: '被识别', desc: '你的能力被系统识别' },
        { icon: '02', title: '被记录', desc: '你的判断、能力、轨迹被长期记录' },
        { icon: '03', title: '被排序', desc: '进入全球排名体系' },
        { icon: '04', title: '被连接', desc: '进入真正高质量人群' },
        { icon: '05', title: '被找到', desc: '项目 / 创业 / 合作自动靠近你' },
      ],
      quote: '"你获得的不只是体验，而是一个可以持续产生回报的能力系统"',
    },
    conference: {
      label: '未来能力大会',
      title1: '只有极少数人',
      title2: '能进入的大会',
      cards: [
        { title: '顶级人群密度', desc: '每一个参与者都经过系统筛选与验证' },
        { title: '思想碰撞', desc: '真正高密度的认知交流与判断训练' },
        { title: '真实机会', desc: '项目、创业、合作在这里真实发生' },
      ],
      highlight: '不是活动，是"筛选后的世界"',
    },
   lifeos: {
  label: 'Life OS',
  title1: '这不是社区，',
  title2: '而是一个你会长期待的环境',
  tags: ['讨论', '判断', '连接'],
  closing: '你开始生活在一个更高密度的世界里',
  quote: '"你在这里做的每一件事，都会变成你的长期资产。"',
  quote2: '不是你去找机会，而是机会根据你的能力分配给你。',
},
    equity: {
      label: '股权分配机制',
      title1: '如果你在 Meta Platforms 早期',
      title2: '拿到',
      title3: '，今天会发生什么？',
      desc: '在一些时间点，这样的份额，可能意味着数千万美元级别的价值',
      disclaimer: '（我们的公司可能达到这样的规模，也可能达不到）',
      tableLabel: '股权释放机制',
      rows: [
        { label: '初始生态激励池', value: '20%', note: '即时生效' },
        { label: '估值达到 50 亿美元', value: '+5%', note: '里程碑释放' },
        { label: '估值达到 100 亿美元', value: '+5%', note: '里程碑释放' },
        { label: '总生态股权池', value: '25–27%', note: '写进机制' },
      ],
      card1Title: '真正重要的不是结果，而是——',
      card1Desc: '你有没有机会，在一切还没发生之前进入分配体系',
      card2Label: '进入方式',
      card2Desc: '在这里，你不是用钱进入，',
      card2Highlight: '而是用能力和参与进入',
      card2Sub: '今天参与，是用能力换份额。\n以后参与，是用钱买别人的份额。',
      card3Sub: '股权不是起点，而是能力被长期验证后的结果',
      card3Desc: '激励体系包括：能力记录、信用体系、\n机会分配、长期回报机制',
    },
    partner: {
      label: '全球合作结构',
      title: '三层合作体系',
      desc: '我们正在寻找长期合作伙伴，共同构建这一能力系统。',
      tiers: [
        {
          id: 'regional',
          layer: '第一层',
          name: 'Regional Partners',
          nameZh: '片区合作',
          items: ['全球约 5 个区域', '负责区域协调与资源'],
          target: '家族 / 长期资源方',
          target_label: '对象',
        },
        {
          id: 'city',
          layer: '第二层',
          name: 'City Partners',
          nameZh: '城市合作',
          items: ['每城市核心合作方', '用户获取', '社区连接', '本地资源'],
          target: '城市统筹者',
          target_label: '对象',
        },
        {
          id: 'equity',
          layer: '第三层',
          name: 'Equity Contributors',
          nameZh: '股权贡献',
          items: ['股权池', '关键资源', '长期贡献'],
          target: '长期生态贡献者',
          target_label: '对象',
        },
      ],
      cityTitle: '每个城市三类角色，City Partner 负责统筹',
      cityLabel: '城市执行结构',
      cityRoles: [
        { role: '训练合作伙伴', desc: '用户 — 参与训练体系' },
        { role: '社区', desc: '人才 — 构建社区网络' },
        { role: '城市节点', desc: '资源 — 提供本地资源' },
      ],
    },
    incentive: {
      label: '激励机制',
      title: '短期 · 中期 · 长期',
      desc: '我们采用短期激励 + 利润分配 + 股权绑定的结构',
      levels: [
        { period: '短期', type: '推荐奖励', desc: '有效用户推荐，与转化绑定' },
        { period: '中期', type: '城市利润分配', desc: '城市收益的 20% 进入分配池' },
        { period: '长期', type: '股权激励', desc: '生态贡献者获得股权奖励' },
      ],
      stepsLabel: '推荐奖励三阶段',
      steps: [
        { num: '01', title: '注册', desc: '奖励有效注册用户' },
        { num: '02', title: '参与', desc: '完成首次参与后触发奖励' },
        { num: '03', title: '转化', desc: '成为付费成员后获得最高奖励' },
      ],
      principle: '原则：奖励「有效用户」· 不奖励纯注册 · 与转化绑定',
      distLabel: '城市利润分配机制',
      step1: '第一步：基础成本优先保障（讲师费用 / 场地费用）',
      step2: '第二步：利润的 20% 进入分配池',
      distribution: [
        { label: '城市负责人', value: '40%' },
        { label: '训练合作伙伴', value: '30%' },
        { label: '社区', value: '20%' },
        { label: '弹性池', value: '10%' },
      ],
      distNote: '可根据实际调整，原则不变',
      equityLabel: '长期股权',
      equityDesc: '生态贡献者获得股权激励，具体比例根据贡献协商确定。',
    },
    value: {
      label: '价值统一',
      title1: '你不是来赚钱的，',
      title2: '你是来成为',
      title3: '「值得被分配的人」',
      desc: '一旦你成为那种人——机会、资源、股权，都会来找你',
      quotes: [
        '不是你去找机会，而是机会根据你的能力分配给你。',
        '我们不是在分钱，我们在分未来的参与权。',
        '不是复制 Meta，而是进入下一次机会的早期结构。',
        '别人惩罚失败，我们利用失败。',
      ],
    },
    contact: {
      label: '联系我们',
      title1: '进入系统，',
      title2: '成为被识别的人',
      desc: '如果你只是想赚钱，这里不适合你。\n如果你想进入未来分配体系，这里才适合你。',
      namePlaceholder: '你的姓名',
      cityPlaceholder: '所在城市 / 区域',
      roleDefault: '参与方向',
      roles: [
        { value: 'regional', label: '区域合作伙伴' },
        { value: 'city', label: '城市合作伙伴' },
        { value: 'equity', label: '股权贡献者' },
        { value: 'training', label: '训练参与者' },
      ],
      messagePlaceholder: '简述你的背景与参与想法',
      btnSubmit: '进入系统 / 参与股权分配',
      btnSubmitting: '提交中...',
      successTitle: '申请已提交',
      successDesc: '我们会在 3 个工作日内与你联系。',
      alertMsg: '请填写姓名、城市和参与方向。',
      errorMsg: '出现错误，请重试或直接发送邮件联系我们。',
      disclaimer: '所有合作结构、利润分配与股权激励，将根据具体合作与贡献进一步协商确定。Novara 保留最终解释权。',
    },
    footer: {
      copy: '© 2026 Novara. 保留所有权利。',
    },
  },

  en: {
    nav: {
      brand: 'NOVARA',
      items: [
        { id: 'identity', label: 'Identity' },
        { id: 'equity', label: 'Equity' },
        { id: 'partner', label: 'Partnership' },
        { id: 'incentive', label: 'Incentive' },
      ],
      apply: 'Enter System',
      darkMode: 'Switch to Dwark Mode',
      lightMode: 'Switch to Light Mode',
      langToggle: '中文',
    },
    hero: {
      badge: 'Global Future Capability Ranking & Recognition System',
      title1: 'In the Age of AI,',
      title2: 'The True Scarcity Is Not Capability —',
      title3: 'It\'s Capability Recognized by the System, Acknowledged by the World',
      desc: 'We are building a global future capability ranking and recognition system.',
      btn: 'Enter System',
      stats: [
        { num: 'Top 1%', label: 'Global Capability Ranking' },
        { num: '25–27%', label: 'Ecosystem Equity Pool' },
        { num: '5 Core', label: 'Value Systems' },
        { num: 'Long-term', label: 'Capability Asset Accumulation' },
      ],
    },
    identity: {
      label: 'Identity Recognition',
      title1: 'If You Are in the Global Top 1%,',
      title2: 'Will the World Know?',
      desc: 'Here — who you are, how strong you are, what you have done, will all be recorded.',
      highlight: 'It\'s not that you think you\'re strong — the system proves it.',
      values: [
        { icon: '01', title: 'Recognized', desc: 'Your capabilities are recognized by the system' },
        { icon: '02', title: 'Recorded', desc: 'Your judgment, abilities, and trajectory are documented long-term' },
        { icon: '03', title: 'Ranked', desc: 'Enter the global ranking system' },
        { icon: '04', title: 'Connected', desc: 'Enter a truly high-quality network' },
        { icon: '05', title: 'Found', desc: 'Projects / startups / collaborations come to you automatically' },
      ],
      quote: '"What you gain here is not just an experience, but a capability system that generates returns continuously."',
    },
    conference: {
      label: 'Future Capability Summit',
      title1: 'A Summit Only',
      title2: 'A Few Can Enter',
      cards: [
        { title: 'Elite Density', desc: 'Every participant has been vetted and verified by the system' },
        { title: 'Collision of Ideas', desc: 'High-density cognitive exchange and judgment training' },
        { title: 'Real Opportunities', desc: 'Projects, startups, and collaborations happen here for real' },
      ],
      highlight: 'Not an event — it\'s a "filtered world"',
    },
 lifeos: {
  label: 'Life OS',
  title1: 'This Is Not a Community —',
  title2: 'It\'s an Environment You\'ll Stay In Long-term',
  tags: ['Discuss', 'Judge', 'Connect'],
  closing: 'You begin living in a higher-density world.',
  quote: '"Everything you do here becomes a long-term asset."',
  quote2: 'You don\'t chase opportunities — opportunities are allocated to you based on your capabilities.',
},
    equity: {
      label: 'Equity Distribution',
      title1: 'If You Had 0.001% of Meta Platforms',
      title2: 'in the Early Days,',
      title3: 'What Would That Mean Today?',
      desc: 'At certain points in time, such a stake could be worth tens of millions of dollars.',
      disclaimer: '(Our company may or may not reach that scale.)',
      tableLabel: 'Equity Release Mechanism',
      rows: [
        { label: 'Initial Ecosystem Incentive Pool', value: '20%', note: 'Effective immediately' },
        { label: 'Valuation reaches $5B', value: '+5%', note: 'Milestone release' },
        { label: 'Valuation reaches $10B', value: '+5%', note: 'Milestone release' },
        { label: 'Total Ecosystem Equity Pool', value: '25–27%', note: 'Built into the mechanism' },
      ],
      card1Title: 'What truly matters is not the outcome — it\'s',
      card1Desc: 'Whether you had the chance to enter the distribution system before everything happened.',
      card2Label: 'How to Enter',
      card2Desc: 'Here, you don\'t enter with money —',
      card2Highlight: 'you enter with capability and participation.',
      card2Sub: 'Join today: exchange capability for equity.\nJoin later: buy someone else\'s equity with money.',
      card3Sub: 'Equity is not the starting point — it\'s the result of long-term verified capability.',
      card3Desc: 'The incentive system includes: capability records, credit system,\nopportunity distribution, and long-term return mechanisms.',
    },
    partner: {
      label: 'Global Partnership Structure',
      title: 'Three-Tier Partnership System',
      desc: 'We are looking for long-term partners to build this capability system together.',
      tiers: [
        {
          id: 'regional',
          layer: 'Layer 1',
          name: 'Regional Partners',
          nameZh: 'Regional',
          items: ['Approx. 5 global regions', 'Regional coordination & resources'],
          target: 'Family offices / long-term capital',
          target_label: 'For',
        },
        {
          id: 'city',
          layer: 'Layer 2',
          name: 'City Partners',
          nameZh: 'City',
          items: ['Core partner per city', 'User acquisition', 'Community building', 'Local resources'],
          target: 'City coordinator',
          target_label: 'For',
        },
        {
          id: 'equity',
          layer: 'Layer 3',
          name: 'Equity Contributors',
          nameZh: 'Equity',
          items: ['Equity pool', 'Key resources', 'Long-term contribution'],
          target: 'Long-term ecosystem contributors',
          target_label: 'For',
        },
      ],
      cityTitle: 'Three roles per city, City Partner coordinates all',
      cityLabel: 'City Execution Structure',
      cityRoles: [
        { role: 'Training Partner', desc: 'Users — participate in the training system' },
        { role: 'Community', desc: 'Talent — build the community network' },
        { role: 'City Node', desc: 'Resources — provide local resources' },
      ],
    },
    incentive: {
      label: 'Incentive Structure',
      title: 'Short · Mid · Long-term',
      desc: 'We use a structure of short-term incentives + profit sharing + equity alignment.',
      levels: [
        { period: 'Short-term', type: 'Referral Rewards', desc: 'Reward effective user referrals, tied to conversion' },
        { period: 'Mid-term', type: 'City Profit Sharing', desc: '20% of city revenue enters the distribution pool' },
        { period: 'Long-term', type: 'Equity Incentives', desc: 'Ecosystem contributors receive equity rewards' },
      ],
      stepsLabel: 'Three-Stage Referral Rewards',
      steps: [
        { num: '01', title: 'Registration', desc: 'Reward for effective new user registration' },
        { num: '02', title: 'Participation', desc: 'Reward triggered after first session completion' },
        { num: '03', title: 'Conversion', desc: 'Maximum reward when user becomes a paying member' },
      ],
      principle: 'Principle: Reward "effective users" · No reward for pure registration · Tied to conversion',
      distLabel: 'City Profit Distribution Mechanism',
      step1: 'Step 1: Base costs covered first (instructor fees / venue)',
      step2: 'Step 2: 20% of profits enter the distribution pool',
      distribution: [
        { label: 'City Lead', value: '40%' },
        { label: 'Training Partner', value: '30%' },
        { label: 'Community', value: '20%' },
        { label: 'Flexible Pool', value: '10%' },
      ],
      distNote: 'Adjustable based on actual contributions. Core principles remain unchanged.',
      equityLabel: 'Long-term Equity',
      equityDesc: 'Ecosystem contributors receive equity incentives. Specific ratios negotiated based on contributions.',
    },
    value: {
      label: 'Value Alignment',
      title1: 'You\'re Not Here to Make Money —',
      title2: 'You\'re Here to Become',
      title3: '"Someone Worth Being Allocated To"',
      desc: 'Once you become that person — opportunities, resources, and equity will come to you.',
      quotes: [
        'You don\'t chase opportunities — opportunities are allocated to you based on your capabilities.',
        'We\'re not distributing money — we\'re distributing future participation rights.',
        'Not replicating Meta — entering the early structure of the next opportunity.',
        'Others punish failure. We leverage it.',
      ],
    },
    contact: {
      label: 'Contact Us',
      title1: 'Enter the System,',
      title2: 'Become Someone Who Gets Recognized',
      desc: 'If you\'re just here to make money, this isn\'t for you.\nIf you want to enter the future distribution system, this is the place.',
      namePlaceholder: 'Your name',
      cityPlaceholder: 'City / Region',
      roleDefault: 'Partnership type',
      roles: [
        { value: 'regional', label: 'Regional Partner' },
        { value: 'city', label: 'City Partner' },
        { value: 'equity', label: 'Equity Contributor' },
        { value: 'training', label: 'Training Partner' },
      ],
      messagePlaceholder: 'Briefly describe your background and participation ideas',
      btnSubmit: 'Enter System / Join Equity Distribution',
      btnSubmitting: 'Submitting...',
      successTitle: 'Application Submitted',
      successDesc: 'We will get back to you within 3 business days.',
      alertMsg: 'Please fill in your name, city, and partnership type.',
      errorMsg: 'Something went wrong. Please try again or email us directly.',
      disclaimer: 'All partnership structures, profit sharing, and equity incentives will be further negotiated based on specific contributions. Novara reserves the right of final interpretation.',
    },
    footer: {
      copy: '© 2026 Novara. All rights reserved.',
    },
  },
}

export default lang