const lang = {
  zh: {
    nav: {
      brand: 'NOVARA',
items: [
  { id: 'identity', label: '能力体系' },
  { id: 'phases', label: '产品路径' },
  { id: 'partner', label: '全球合作' },
  { id: 'incentive', label: '激励机制' },
],
      apply: '立即申请',
      darkMode: '切换到深色模式',
      lightMode: '切换到浅色模式',
      langToggle: 'EN',
    },
    hero: {
      badge: '面向 AI 时代的人类能力系统',
      title1: 'AI 时代，真正稀缺的不是能力，',
      title2: '而是——',
      title3: '被系统识别、被世界承认的能力',
      desc: '我们在做一件事：建立全球未来能力排名与识别系统',
      btn: '探索系统',
      btnSecondary: '了解更多',
      stats: [
        { num: 'Top 1%', label: '全球能力排名' },
        { num: '5层', label: '能力架构体系' },
        { num: '4阶段', label: '产品发展路径' },
        { num: '全球', label: '合作伙伴网络' },
      ],
    },
    identity: {
      label: '身份识别',
      title1: '如果你是全球 Top 1%，',
      title2: '世界会知道吗？',
      desc: '在这里——你是谁、你有多强、你做过什么，都会被记录',
      highlight: '不是你觉得你强，是系统证明你强。',
      intro: '你获得的不只是体验，而是一个可以持续产生回报的能力系统',
      values: [
        { icon: '01', title: '被识别', desc: '你的能力被系统识别，形成可验证的能力证明' },
        { icon: '02', title: '被记录', desc: '你的判断、能力、成长轨迹被长期存档' },
        { icon: '03', title: '被排序', desc: '进入全球排名体系（Top X% / Judgment Level）' },
        { icon: '04', title: '被连接', desc: '进入真正高质量、高密度人群网络' },
        { icon: '05', title: '被找到', desc: '项目 / 创业 / 合作自动靠近你' },
      ],
      quote: '"你获得的不只是体验，而是一个可以持续产生回报的能力系统"',
    },
    layers: {
      label: '能力架构',
      title1: '五层能力架构',
      title2: '训练 AI 无法替代的能力，构建长期能力系统',
      items: [
        {
          num: '01',
          title: '核心认知能力 · Human Core',
          sub: '看懂问题 · 发现错误 · 举一反三 · 判断是否真正掌握',
          tag: '当前重点',
        },
        {
          num: '02',
          title: 'AI / Agent 指挥能力',
          sub: '精准提问 · 拆解任务 · 验证输出结果',
          tag: 'Phase 2',
        },
        {
          num: '03',
          title: '能力进化系统 · Capability System',
          sub: '识别错误模式 · 规划训练路径 · 追踪成长轨迹',
          tag: 'Phase 3',
        },
        {
          num: '04',
          title: '心智与判断能力 · Mind & Judgment',
          sub: '长期决策 · 结构化判断 · 建立责任能力',
          tag: 'Phase 4',
        },
        {
          num: '05',
          title: '个人孪生 Agent · 未来层',
          sub: '自动信息获取 · 任务处理 · 个性化决策支持',
          tag: '未来',
        },
      ],
      closing: '看懂问题、发现错误、举一反三、判断是否真正掌握',
    },
    phases: {
      label: '产品路径',
      title1: '四阶段产品路径',
      items: [
        {
          id: 'phase-1',
          label: 'Phase 1 · 现在',
          name: '立即开始',
          items: ['每天 20 分钟训练', '核心认知能力', '基础能力画像'],
          current: true,
        },
        {
          id: 'phase-2',
          label: 'Phase 2 · 短期',
          name: '系统训练',
          items: ['系统能力训练', 'AI 协同能力', '从"学会"到"能用"'],
          current: false,
        },
        {
          id: 'phase-3',
          label: 'Phase 3 · 中期',
          name: '能力系统',
          items: ['完整能力系统', '路径持续优化', '长期积累追踪'],
          current: false,
        },
        {
          id: 'phase-4',
          label: 'Phase 4 · 长期',
          name: '长期精进',
          items: ['高阶判断能力', '复杂问题处理', '建立责任体系'],
          current: false,
        },
      ],
    },
    conference: {
      label: '未来能力峰会',
      title1: '只有极少数人',
      title2: '能进入的大会',
      cards: [
        { title: '顶级人群密度', desc: '每一个参与者都经过系统筛选与验证' },
        { title: '思想碰撞', desc: '真正高密度的认知交流与判断训练' },
        { title: '真实机会', desc: '项目、创业、合作在这里真实发生' },
        { title: '全球网络', desc: '连接全球顶级人才与资源网络' },
      ],
      highlight: '不是活动，是"筛选后的世界"',
    },
    lifeos: {
      label: 'Life OS',
      title1: '这不是社区，',
      title2: '而是一个你会长期待的环境',
      tags: [
        { title: '讨论', desc: '与顶尖思考者共同探索问题边界，突破认知上限' },
        { title: '判断', desc: '持续磨砺对复杂问题的判断力，形成系统化思维' },
        { title: '连接', desc: '与真正有实力的全球人群建立长期深度关系' },
      ],
      closing: '你开始生活在一个更高密度的世界里',
      quote: '"你在这里做的每一件事，都会变成你的长期资产。"',
      quote2: '不是你去找机会，而是机会根据你的能力分配给你。',
    },
    partner: {
      label: '全球合作结构',
      title: '三层合作体系',
      desc: '我们正在寻找长期合作伙伴，共同构建这一能力系统。',
      tiers: [
        {
          id: 'regional',
          layer: '第一层',
          name: 'Regional Partners',
          nameZh: '片区合作',
          items: ['全球约 5 个区域', '区域协调与资源统筹'],
          target: '家族办公室 / 长期资源方',
          target_label: '适合对象',
        },
        {
          id: 'city',
          layer: '第二层',
          name: 'City Partners',
          nameZh: '城市合作',
          items: ['每城市核心合作方', '用户获取', '社区连接', '本地资源整合'],
          target: '城市统筹者',
          target_label: '城市角色',
        },
        {
          id: 'strategic',
          layer: '第三层',
          name: 'Strategic Contributors',
          nameZh: '战略贡献',
          items: ['关键资源方', '长期战略贡献者', '推动系统全球落地'],
          target: '战略资源合作方',
          target_label: '适合对象',
        },
      ],
      cityTitle: '每个城市三类角色，City Partner 负责统筹',
      cityLabel: '城市执行结构',
      cityRoles: [
        { role: 'Training Partner', desc: '用户 — 参与训练体系' },
        { role: 'Community', desc: '人才 — 构建社区网络' },
        { role: 'City Node', desc: '资源 — 提供本地资源' },
      ],
      disclaimer: '所有合作结构、利润分配与股权激励，将根据具体合作与贡献进一步协商确定。Novara 保留最终解释权。',
    },
    incentive: {
      label: '激励机制',
      title: '短期 · 中期 · 长期',
      desc: '我们采用短期激励 + 利润分配 + 股权绑定的结构',
      levels: [
        { period: '短期', type: '推荐奖励', desc: '有效用户推荐，与转化绑定' },
        { period: '中期', type: '城市利润分配', desc: '城市收益的 20% 进入分配池' },
        { period: '长期', type: '股权激励', desc: '生态贡献者获得股权奖励' },
      ],
      stepsLabel: '推荐奖励三阶段',
      steps: [
        { num: '01', title: '注册', desc: '奖励有效注册用户' },
        { num: '02', title: '参与', desc: '完成首次参与后触发奖励' },
        { num: '03', title: '转化', desc: '成为付费成员后获得最高奖励' },
      ],
      principle: '原则：奖励「有效用户」· 不奖励纯注册 · 与转化绑定',
      distLabel: '城市利润分配机制',
      step1: '第一步：基础成本优先保障（讲师费用 / 场地费用）',
      step2: '第二步：利润的 20% 进入分配池',
      distribution: [
        { label: '城市负责人', value: '40%' },
        { label: '训练合作伙伴', value: '30%' },
        { label: '社区', value: '20%' },
        { label: '弹性池', value: '10%' },
      ],
      distNote: '可根据实际调整，原则不变',
      equityLabel: '长期股权',
      equityDesc: '生态贡献者获得股权激励，具体比例根据贡献协商确定。',
    },
    contact: {
      label: '联系我们',
      title1: '进入系统，',
      title2: '成为被识别的人',
      desc: '提交时请包含你所在城市／区域、核心资源能力，以及合作方向。',
      email: 'business@novara.tech',
      namePlaceholder: '你的姓名',
      cityPlaceholder: '所在城市 / 区域',
      roleDefault: '合作方向',
      roles: [
        { value: 'city', label: 'City Partner' },
        { value: 'regional', label: 'Regional Partner' },
        { value: 'strategic', label: 'Strategic Contributor' },
      ],
      messagePlaceholder: '你能带来的核心资源与合作想法',
      btnSubmit: '进入系统',
      btnSubmitting: '提交中...',
      successTitle: '申请已提交',
      successDesc: '我们会在 3 个工作日内与你联系。',
      alertMsg: '请填写姓名、城市和合作方向。',
      errorMsg: '出现错误，请重试或直接发送邮件联系我们。',
      disclaimer: '所有合作结构、利润分配与股权激励，将根据具体合作与贡献进一步协商确定。Novara 保留最终解释权。',
    },
    footer: {
      brand: 'NOVARA',
      tagline: 'Novara 关注的不是学什么，而是人在 AI 时代应具备什么能力。',
      copy: '© 2026 Novara. All rights reserved.',
    },
  },

  en: {
    nav: {
      brand: 'NOVARA',
items: [
  { id: 'identity', label: 'Capability' },
  { id: 'phases', label: 'Roadmap' },
  { id: 'partner', label: 'Partnership' },
  { id: 'incentive', label: 'Incentive' },
],
apply: 'Apply Now',
      darkMode: 'Switch to Dark Mode',
      lightMode: 'Switch to Light Mode',
      langToggle: '中文',
    },
    hero: {
      badge: 'Human Capability System for the Age of AI',
      title1: 'In the Age of AI, True Scarcity Is Not Capability —',
      title2: 'It\'s',
      title3: 'Capability Recognized by the System, Acknowledged by the World',
      desc: 'We are building a global future capability ranking and recognition system.',
      btn: 'Explore the System',
      btnSecondary: 'Learn More',
      stats: [
        { num: 'Top 1%', label: 'Global Capability Ranking' },
        { num: '5 Layers', label: 'Capability Architecture' },
        { num: '4 Phases', label: 'Product Roadmap' },
        { num: 'Global', label: 'Partner Network' },
      ],
    },
    identity: {
      label: 'Identity Recognition',
      title1: 'If You Are in the Global Top 1%,',
      title2: 'Will the World Know?',
      desc: 'Here — who you are, how strong you are, what you have done, will all be recorded.',
      highlight: 'It\'s not that you think you\'re strong — the system proves it.',
      intro: 'What you gain here is not just an experience, but a capability system that generates returns continuously.',
      values: [
        { icon: '01', title: 'Recognized', desc: 'Your capabilities are recognized by the system, forming verifiable proof' },
        { icon: '02', title: 'Recorded', desc: 'Your judgment, abilities, and growth trajectory are archived long-term' },
        { icon: '03', title: 'Ranked', desc: 'Enter the global ranking system (Top X% / Judgment Level)' },
        { icon: '04', title: 'Connected', desc: 'Enter a truly high-quality, high-density human network' },
        { icon: '05', title: 'Found', desc: 'Projects / startups / collaborations come to you automatically' },
      ],
      quote: '"What you gain here is not just an experience, but a capability system that generates returns continuously."',
    },
    layers: {
      label: 'Capability Architecture',
      title1: 'Five-Layer Capability Architecture',
      title2: 'Train what AI cannot replace. Build long-term capability systems.',
      items: [
        {
          num: '01',
          title: 'Human Core · Core Cognition',
          sub: 'Read the problem · Spot errors · Transfer knowledge · Verify mastery',
          tag: 'Current Focus',
        },
        {
          num: '02',
          title: 'AI / Agent Command',
          sub: 'Precise prompting · Task decomposition · Output validation',
          tag: 'Phase 2',
        },
        {
          num: '03',
          title: 'Capability Evolution System',
          sub: 'Error pattern recognition · Training path planning · Growth tracking',
          tag: 'Phase 3',
        },
        {
          num: '04',
          title: 'Mind & Judgment',
          sub: 'Long-term decisions · Structural thinking · Accountability',
          tag: 'Phase 4',
        },
        {
          num: '05',
          title: 'Personal Twin Agent · Future Layer',
          sub: 'Automated information retrieval · Task execution · Personalized decision support',
          tag: 'Future',
        },
      ],
      closing: 'Read the problem · Spot errors · Transfer knowledge · Verify mastery',
    },
    phases: {
      label: 'Product Path',
      title1: 'Four-Phase Product Roadmap',
      items: [
        {
          id: 'phase-1',
          label: 'Phase 1 · Now',
          name: 'Start Now',
          items: ['20 minutes daily training', 'Core cognitive skills', 'Baseline capability profile'],
          current: true,
        },
        {
          id: 'phase-2',
          label: 'Phase 2 · Short-term',
          name: 'Systematic Training',
          items: ['Systematic capability training', 'AI collaboration skills', 'From learning to applying'],
          current: false,
        },
        {
          id: 'phase-3',
          label: 'Phase 3 · Mid-term',
          name: 'Capability System',
          items: ['Full capability system', 'Continuous path optimization', 'Long-term accumulation tracking'],
          current: false,
        },
        {
          id: 'phase-4',
          label: 'Phase 4 · Long-term',
          name: 'Mastery',
          items: ['Advanced judgment skills', 'Complex problem solving', 'Accountability systems'],
          current: false,
        },
      ],
    },
    conference: {
      label: 'Future Capability Summit',
      title1: 'A Summit Only',
      title2: 'A Few Can Enter',
      cards: [
        { title: 'Elite Density', desc: 'Every participant has been vetted and verified by the system' },
        { title: 'Collision of Ideas', desc: 'High-density cognitive exchange and judgment training' },
        { title: 'Real Opportunities', desc: 'Projects, startups, and collaborations happen here for real' },
        { title: 'Global Network', desc: 'Connect with top global talent and resource networks' },
      ],
      highlight: 'Not an event — it\'s a "filtered world"',
    },
    lifeos: {
      label: 'Life OS',
      title1: 'This Is Not a Community —',
      title2: 'It\'s an Environment You\'ll Stay In Long-term',
      tags: [
        { title: 'Discuss', desc: 'Explore the boundaries of problems with top thinkers, break through cognitive limits' },
        { title: 'Judge', desc: 'Continuously sharpen your judgment on complex problems, build systematic thinking' },
        { title: 'Connect', desc: 'Build long-term deep relationships with truly capable people globally' },
      ],
      closing: 'You begin living in a higher-density world.',
      quote: '"Everything you do here becomes a long-term asset."',
      quote2: 'You don\'t chase opportunities — opportunities are allocated to you based on your capabilities.',
    },
    partner: {
      label: 'Global Partnership',
      title: 'Global Partnership Structure',
      desc: 'We are looking for long-term partners to build this capability system together.',
      tiers: [
        {
          id: 'regional',
          layer: 'Layer 1',
          name: 'Regional Partners',
          nameZh: 'Regional',
          items: ['Approx. 5 global regions', 'Regional coordination & resource integration'],
          target: 'Family offices / long-term capital',
          target_label: 'For',
        },
        {
          id: 'city',
          layer: 'Layer 2',
          name: 'City Partners',
          nameZh: 'City',
          items: ['Core partner per city', 'User acquisition', 'Community building', 'Local resource integration'],
          target: 'City coordinator',
          target_label: 'Role',
        },
        {
          id: 'strategic',
          layer: 'Layer 3',
          name: 'Strategic Contributors',
          nameZh: 'Strategic',
          items: ['Key resource providers', 'Long-term strategic contributors', 'Drive global system deployment'],
          target: 'Strategic resource partners',
          target_label: 'For',
        },
      ],
      cityTitle: 'Three roles per city, City Partner coordinates all',
      cityLabel: 'City Execution Structure',
      cityRoles: [
        { role: 'Training Partner', desc: 'Users — participate in the training system' },
        { role: 'Community', desc: 'Talent — build the community network' },
        { role: 'City Node', desc: 'Resources — provide local resources' },
      ],
      disclaimer: 'All partnership structures, profit sharing, and equity incentives will be further negotiated based on specific contributions. Novara reserves the right of final interpretation.',
    },
    incentive: {
      label: 'Incentive Structure',
      title: 'Short · Mid · Long-term',
      desc: 'We use a structure of short-term incentives + profit sharing + equity alignment.',
      levels: [
        { period: 'Short-term', type: 'Referral Rewards', desc: 'Reward effective user referrals, tied to conversion' },
        { period: 'Mid-term', type: 'City Profit Sharing', desc: '20% of city revenue enters the distribution pool' },
        { period: 'Long-term', type: 'Equity Incentives', desc: 'Ecosystem contributors receive equity rewards' },
      ],
      stepsLabel: 'Three-Stage Referral Rewards',
      steps: [
        { num: '01', title: 'Registration', desc: 'Reward for effective new user registration' },
        { num: '02', title: 'Participation', desc: 'Reward triggered after first session completion' },
        { num: '03', title: 'Conversion', desc: 'Maximum reward when user becomes a paying member' },
      ],
      principle: 'Principle: Reward "effective users" · No reward for pure registration · Tied to conversion',
      distLabel: 'City Profit Distribution Mechanism',
      step1: 'Step 1: Base costs covered first (instructor fees / venue)',
      step2: 'Step 2: 20% of profits enter the distribution pool',
      distribution: [
        { label: 'City Lead', value: '40%' },
        { label: 'Training Partner', value: '30%' },
        { label: 'Community', value: '20%' },
        { label: 'Flexible Pool', value: '10%' },
      ],
      distNote: 'Adjustable based on actual contributions. Core principles remain unchanged.',
      equityLabel: 'Long-term Equity',
      equityDesc: 'Ecosystem contributors receive equity incentives. Specific ratios negotiated based on contributions.',
    },
    contact: {
      label: 'Contact',
      title1: 'Enter the System,',
      title2: 'Become Someone Who Gets Recognized',
      desc: 'Please include your city/region, core resources, and partnership direction.',
      email: 'business@novara.tech',
      namePlaceholder: 'Your name',
      cityPlaceholder: 'City / Region',
      roleDefault: 'Partnership direction',
      roles: [
        { value: 'city', label: 'City Partner' },
        { value: 'regional', label: 'Regional Partner' },
        { value: 'strategic', label: 'Strategic Contributor' },
      ],
      messagePlaceholder: 'Your core resources and partnership ideas',
      btnSubmit: 'Enter System',
      btnSubmitting: 'Submitting...',
      successTitle: 'Application Submitted',
      successDesc: 'We will get back to you within 3 business days.',
      alertMsg: 'Please fill in your name, city, and partnership direction.',
      errorMsg: 'Something went wrong. Please try again or email us directly.',
      disclaimer: 'All partnership structures, profit sharing, and equity incentives will be further negotiated based on specific contributions. Novara reserves the right of final interpretation.',
    },
    footer: {
      brand: 'NOVARA',
      tagline: 'Novara is not about what to learn — it\'s about what capabilities humans need in the age of AI.',
      copy: '© 2026 Novara. All rights reserved.',
    },
  },
}

export default lang