const lang = {
  zh: {
intro: {
  lines: [
    '大多数人不会缺知识。',
    '会缺判断。',
    '',
    'AI 学会了所有人写过的东西。',
    '但有些东西，它永远看不见。',
    '',
    '那才是真正价值所在。',
    '',
    '我们正在打造某种东西，让这种能力被看见。',
    '如果你知道我在说什么——我们想找到你。',
  ],
  skip: '跳过',
  enter: '进入',
},

    nav: {
      brand: 'NOVARA',
      items: [
        { id: 'identity', label: '为什么现在' },
        { id: 'phases', label: '核心能力体系' },
        { id: 'partner', label: '城市合作' },
        { id: 'incentive', label: '激励机制' },
      ],
      apply: '立即申请',
      darkMode: '切换到深色模式',
      lightMode: '切换到浅色模式',
      langToggle: 'EN',
    },
hero: {
  badge: '全球能力网络',
  title1: '一个新的全球网络',
  title2: '正在形成。',
  title3: '',
  desc: '在 AI 时代，最有价值的能力不再是知识，而是在复杂系统中理解、判断和行动的能力。\n\nNovara 正在构建一个全球能力网络，为真正卓越的人提供被看见、被连接、被放大的机会。',
  btn: '申请成为城市合作伙伴',
  btnSecondary: '了解更多',
  stats: [
  { num: '2026', label: '全球峰会启动' },
  { num: 'Limited', label: '城市合作名额有限' },
  { num: '3', label: '核心能力体系' },
  { num: 'Global', label: '合作伙伴网络' },
],
},
identity: {
  label: '时代背景',
  title1: '为什么是现在',
  title2: '',
  desc: '当人工智能不断扩展知识与执行能力，\n人类的优势正在转向更深层的结构。\n\n不再是知道什么，\n而是如何理解问题、做出判断，\n以及在复杂系统中持续演化。',
  highlight: '稀缺的不再是信息，而是判断力。',
  intro: 'Novara 所处的，正是这一层。',
  values: [
    { icon: '01', title: '判断力', desc: '在复杂情境中做出准确判断的能力' },
    { icon: '02', title: '结构理解能力', desc: '穿透表象，理解问题底层结构的能力' },
    { icon: '03', title: '长期认知能力', desc: '持续演化、不断积累的认知能力' },
    { icon: '04', title: '人与 AI 协同', desc: '在 AI 时代发挥人类独特优势的高阶能力' },
    { icon: '05', title: '能力连接机会', desc: '将能力转化为长期积累与重要机会的系统' },
  ],
  quote: '"稀缺的不再是信息，而是判断力。"',
},
phases: {
  label: '核心能力体系',
  title1: 'Novara 关注的是一个更基础的问题',
  subtitle: '在 AI 时代，什么样的能力才真正具有价值，以及这些能力如何连接到更重要的机会，并形成长期积累。',
  closing: 'Novara 正在逐步形成一套新的能力语言，用于描述在 AI 时代真正产生价值的能力结构。这些语言并非来自理论设计，而是透过实际问题和实践经验逐步形成。',
  items: [
    {
      id: 'phase-1',
      label: '核心能力',
      name: '判断力',
      items: ['理解复杂问题的本质', '在不确定中做出决策', '持续验证与修正判断'],
      current: true,
    },
    {
      id: 'phase-2',
      label: '核心能力',
      name: '结构理解',
      items: ['穿透表象识别底层逻辑', '建立跨领域的结构认知', '在复杂系统中定位关键'],
      current: false,
    },
    {
      id: 'phase-3',
      label: '核心能力',
      name: '长期认知',
      items: ['持续演化的认知系统', '能力的长期积累与复利', '跨时间维度的判断能力'],
      current: false,
    },
    {
      id: 'phase-4',
      label: '核心能力',
      name: '人与 AI 协同',
      items: ['发挥人类独特优势', '在 AI 扩展中保持核心价值', '高阶能力的持续放大'],
      current: false,
    },
  ],
},
    conference: {
      label: '三个核心组成部分',
      title1: '我们在构建什么',
      title2: '',
      cards: [
        { title: '能力评估', desc: '一套系统化的能力识别与评估体系' },
        { title: '高潜力网络', desc: '连接全球卓越个体的高质量人群网络' },
        { title: '机会连接层', desc: '将能力与未来机会自动匹配的系统' },
        { title: '不是学校，不是社区，而是能力网络。', desc: '' },
      ],
      highlight: '不是学校。不是社区。而是能力网络。\n\n不是一次课程，也不是一套短期训练。而是一个长期结构：在其中，能力被不断验证、放大，并逐步累积。',
      
    },
    lifeos: {
      label: '全球时间线',
      title1: '接下来会发生什么',
      title2: '',
      tags: [
        {
          title: '2026年9月 · 新词峰会',
          desc: '一项为 AI 时代定义新概念的全球倡议。汇聚思想者、建设者和早期参与者。新词塑造未来的理解方式。',
        },
        {
          title: '2026年12月 · 未来能力峰会',
          desc: '首届专注于 AI 时代能力的全球峰会。受邀参与者包括精选参与者、合作伙伴和贡献者。',
        },
        {
          title: '2026年12月 · 学习理论大会',
          desc: '基于内部研究和早期系统数据的下一代学习框架闭门讨论。',
        },
      ],
      closing: '城市合作伙伴将在这些活动中发挥关键作用。',
      quote: '"早期合作伙伴将获得优先参与权，并共同塑造这些倡议。"',
      quote2: '初始合作伙伴将优先获得参与和共同塑造这些倡议的机会。',
    },
    partner: {
      label: '城市合作',
      title: '为什么需要城市合作伙伴',
      desc: 'Novara 正在通过全球有限数量的城市合作伙伴进行扩张。',
      tiers: [
        {
          id: 'network',
          layer: '职责一',
          name: '建立本地网络',  
          items: ['建立当地能力网络', '识别真正卓越的人', '组织本地活动'],

        },
        {
          id: 'connect',
          layer: '职责二',
          name: '连接人们',
          items: ['连接高质量个体', '建立社区网络', '促进深度合作'],

        },
        {
          id: 'represent',
          layer: '职责三',
          name: '代表 Novara',
          items: ['在当地代表 Novara', '推动系统落地', '参与全球网络'],

        },
      ],
      cityTitle: '我们不是在寻找运营者，我们在寻找长期建设者。',
      cityLabel: '我们在寻找',
      cityRoles: [
        { role: '强大人脉', desc: '具备强大本地与全球网络的个体' },
        { role: '长远视野', desc: '具有长期建设思维的合作伙伴' },
        { role: '能力认知', desc: '理解 AI 时代能力重要性的人' },
      ],
      disclaimer: '所有合作结构、利润分配与股权激励，将根据具体合作与贡献进一步协商确定。Novara 保留最终解释权。',
    },
    incentive: {
      label: '激励机制',
      title: '短期 · 中期 · 长期',
      desc: '我们为长期建设者提供多层次的回报结构。',
      levels: [
        { period: '短期', type: '直接收入', desc: '来自本地项目的直接收益' },
        { period: '中期', type: '城市利润分配', desc: '参与城市层面的利润分配' },
        { period: '长期', type: '全球网络 + 潜在股权', desc: '进入全球网络，获得潜在股权参与机会' },
      ],
      stepsLabel: '名额限制',
      steps: [
        { num: '01', title: '区域合作伙伴', desc: '少量区域级合作伙伴名额' },
        { num: '02', title: '城市核心合作伙伴', desc: '每个城市仅设一个核心合作伙伴' },
        { num: '03', title: '一旦分配不再开放', desc: '城市名额一旦确定，将不再重新开放' },
      ],
      principle: '名额有限，先到先得。',
   distLabel: '城市利润分配',
step1: '基础成本优先保障',
step2: '利润按比例分配给合作伙伴',
distribution: [
  { label: '城市负责人', value: '最高' },
  { label: '训练合作伙伴', value: '次之' },
  { label: '社区', value: '参与分配' },
  { label: '弹性池', value: '按需分配' },
],
distNote: '具体比例将根据贡献协商确定。',
equityLabel: '潜在股权',
equityDesc: '长期贡献者将有机会获得股权参与，具体比例根据贡献协商确定。',
    },
    contact: {
      label: '申请',
      title1: '申请成为',
      title2: '城市合作伙伴',
      desc: '被选中的合作伙伴将直接收到联系。',
      email: 'business@novara.tech',
      namePlaceholder: '你的姓名',
      cityPlaceholder: '城市 / 区域',
      roleDefault: '预期角色',
      emailPlaceholder: '你的邮箱地址',
      subscribeLabel: '同时订阅早期关注者列表，获取最新进展与专属优惠',
      roles: [
        { value: 'city', label: '城市合作伙伴' },
        { value: 'regional', label: '区域合作伙伴' },
        { value: 'community', label: '社区参与者' },
      ],
      messagePlaceholder: '背景、资源、为什么选择 Novara',
      btnSubmit: '立即申请',
      btnSubmitting: '提交中...',
      successTitle: '申请已提交',
      successDesc: '我们会直接联系被选中的合作伙伴。',
      alertMsg: '请填写姓名、城市和预期角色。',
      errorMsg: '出现错误，请重试或直接发送邮件联系我们。',
      disclaimer: 'Novara 运营着一套多层次能力系统，包括学习、评估和长期协调机制。所有合作结构、利润分配与股权激励，将根据具体合作与贡献进一步协商确定。Novara 保留最终解释权。',
    },
waitlist: {
  label: '早期关注者',
  title1: '订阅早期关注者列表',
  title2: '',
  desc: '成为早期关注者，第一时间获得 Novara 的最新进展与活动信息。早期订阅者将享有课程专属优惠。',
  placeholder: '输入你的邮箱地址',
  btn: '立即订阅',
  btnSubmitting: '订阅中...',
  successTitle: '订阅成功',
  successDesc: '欢迎加入 Novara 早期关注者列表。',
  errorMsg: '订阅失败，请重试。',
  badge: '早期专属权益',
  invalidEmail: '请输入有效的邮箱地址',
  perks: [
    { icon: '01', title: '最新进展', desc: '第一时间收到最新研究与活动信息' },
    { icon: '02', title: '专属优惠', desc: '早期订阅者享有课程专属折扣' },
    { icon: '03', title: '优先参与', desc: '优先参与 Novara 活动与内测机会' },
  ],
},

    footer: {
      brand: 'NOVARA',
      tagline: '',
      copy: '© 2026 Novara. All rights reserved.',
    },
  },

  en: {
intro: {
  lines: [
    'Most people don\'t lack knowledge.',
    'They lack judgment.',
    '',
    'AI has learned everything humans have ever written.',
    'But some things, it will never see.',
    '',
    'That is where real value lives.',
    '',
    'We are building something to make that capability visible.',
    'If you know what I\'m talking about — we want to find you.',
  ],
  skip: 'Skip',
  enter: 'Enter',
},

    nav: {
      brand: 'NOVARA',
      items: [
        { id: 'identity', label: 'Why Now' },
        { id: 'phases', label: 'Core Capabilities Framework' },
        { id: 'partner', label: 'City Partners' },
        { id: 'incentive', label: 'Incentive Structure' },
      ],
      apply: 'Apply Now',
      darkMode: 'Switch to Dark Mode',
      lightMode: 'Switch to Light Mode',
      langToggle: '中文',
    },
hero: {
  badge: 'Global Capability Network',
  title1: 'A new global network',
  title2: 'is forming.',
  title3: '',
  desc: 'In the age of AI, the most valuable capability is no longer knowledge, but the ability to understand, decide, and act in complex systems.\n\nNovara is building a global capability network — giving truly exceptional people the opportunity to be seen, connected, and amplified.',
  btn: 'Apply as a City Partner',
  btnSecondary: 'Learn More',
  stats: [
    { num: '2026', label: 'Global Summit Launch' },
    { num: 'Limited', label: 'City Partner Slots' },
    { num: '3 Core', label: 'Capability Components' },
    { num: 'Global', label: 'Partner Network' },
  ],
},
identity: {
  label: 'The Shift',
  title1: 'Why now',
  title2: '',
  desc: 'As artificial intelligence continues to expand knowledge and execution,\nhuman advantage is shifting toward deeper structures.\n\nNo longer what you know,\nbut how you understand problems, make judgments,\nand continuously evolve in complex systems.',
  highlight: 'The scarcity is no longer information — it\'s judgment.',
  intro: 'Novara operates at this layer.',
  values: [
    { icon: '01', title: 'Judgment', desc: 'The ability to make accurate decisions in complex situations' },
    { icon: '02', title: 'Structural Understanding', desc: 'The ability to see through surface and understand underlying structure' },
    { icon: '03', title: 'Long-term Cognition', desc: 'Continuously evolving, accumulating cognitive capability' },
    { icon: '04', title: 'Human-AI Collaboration', desc: 'Higher-order capability leveraging human advantage in the AI era' },
    { icon: '05', title: 'Capability to Opportunity', desc: 'A system connecting capability to long-term accumulation and meaningful opportunities' },
  ],
  quote: '"The scarcity is no longer information — it\'s judgment."',
},
   phases: {
  label: 'Core Capabilities Framework',
  title1: 'Novara focuses on a more fundamental question',
  subtitle: 'In the age of AI, what capabilities truly hold value — and how they connect to meaningful opportunities and form long-term accumulation.',
  closing: 'Novara is gradually developing a new language of capability, to describe the capability structures that truly generate value in the AI era. This language does not come from theoretical design — it emerges through real problems and practice.',
  items: [
    {
      id: 'phase-1',
      label: 'Core Capability',
      name: 'Judgment',
      items: ['Understanding the essence of complex problems', 'Making decisions under uncertainty', 'Continuously verifying and refining judgment'],
      current: true,
    },
    {
      id: 'phase-2',
      label: 'Core Capability',
      name: 'Structural Understanding',
      items: ['Seeing through surface to underlying logic', 'Building cross-domain structural cognition', 'Locating the critical in complex systems'],
      current: false,
    },
    {
      id: 'phase-3',
      label: 'Core Capability',
      name: 'Long-term Cognition',
      items: ['A continuously evolving cognitive system', 'Long-term accumulation and compounding of capability', 'Judgment across time dimensions'],
      current: false,
    },
    {
      id: 'phase-4',
      label: 'Core Capability',
      name: 'Human-AI Collaboration',
      items: ['Leveraging unique human advantages', 'Maintaining core value as AI expands', 'Continuous amplification of higher-order capabilities'],
      current: false,
    },
  ],
},
    conference: {
      label: 'Three core components',
      title1: 'What we are building',
      title2: '',
      cards: [
        { title: 'Capability Assessment', desc: 'A systematic capability identification and assessment framework' },
        { title: 'High-Potential Network', desc: 'A high-quality human network connecting exceptional individuals globally' },
        { title: 'Opportunity Connection Layer', desc: 'A system that automatically matches capability with future opportunities' },
        { title: 'Not a school. Not a community. A capability network.', desc: '' },
      ],
      highlight: 'Not a school. Not a community. A capability network.\n\nNot a course. Not a short-term program. A long-term structure: where capability is continuously verified, amplified, and gradually accumulated.',
    },
    lifeos: {
      label: 'Global Timeline',
      title1: 'What\'s happening next',
      title2: '',
      tags: [
        {
          title: 'September 2026 · New Word Summit',
          desc: 'A global initiative to define new concepts for the AI era. Bringing together thinkers, builders, and early participants. New words shape how the future is understood.',
        },
        {
          title: 'December 2026 · Future Capability Summit',
          desc: 'The first global gathering focused on capability in the AI age. Selected participants, partners, and contributors will be invited.',
        },
        {
          title: 'December 2026 · Learning Theory Conference',
          desc: 'A closed-door discussion on next-generation learning frameworks, based on internal research and early system data.',
        },
      ],
      closing: 'City partners will play a key role in these events.',
      quote: '"Initial partners will have priority access to participate and co-shape these initiatives."',
      quote2: 'Initial partners will have priority access to participate and co-shape these initiatives.',
    },
    partner: {
      label: 'City Partners',
      title: 'Why city partners',
      desc: 'Novara is expanding through a limited number of city partners globally.',
      tiers: [
        {
          id: 'network',
          layer: 'Role 1',
          name: 'Build Local Network',
          items: ['Build the local network', 'Identify truly exceptional people', 'Organize local events'],
  
        },
        {
          id: 'connect',
          layer: 'Role 2',
          name: 'Connect People',
          items: ['Connect high-quality individuals', 'Build community networks', 'Foster deep collaboration'],

        },
        {
          id: 'represent',
          layer: 'Role 3',
          name: 'Represent Novara',
          items: ['Represent Novara locally', 'Drive system deployment', 'Participate in global network'],

        },
      ],
      cityTitle: 'We are not looking for operators. We are looking for long-term builders.',
      cityLabel: 'Who We Are Looking For',
      cityRoles: [
        { role: 'Strong Networks', desc: 'Individuals with strong local and global networks' },
        { role: 'Long-term Vision', desc: 'Partners with a long-term building mindset' },
        { role: 'Capability Awareness', desc: 'People who understand the importance of capability in the AI era' },
      ],
      disclaimer: 'All partnership structures, profit sharing, and equity incentives will be further negotiated based on specific contributions. Novara reserves the right of final interpretation.',
    },
    incentive: {
      label: 'Incentive Structure',
      title: 'Short · Mid · Long-term',
      desc: 'We offer a multi-layer return structure for long-term builders.',
      levels: [
        { period: 'Short-term', type: 'Direct Revenue', desc: 'Direct revenue from local programs' },
        { period: 'Mid-term', type: 'City Profit Sharing', desc: 'Participation in city-level profit distribution' },
        { period: 'Long-term', type: 'Global Network + Equity', desc: 'Access to global network and potential equity participation' },
      ],
      stepsLabel: 'Limited Availability',
      steps: [
        { num: '01', title: 'Regional Partners', desc: 'A small number of regional partner slots available' },
        { num: '02', title: 'One Core City Partner', desc: 'One core partner per city only' },
        { num: '03', title: 'Once Assigned, Not Reopened', desc: 'Once a city is assigned, it will not be reopened' },
      ],
      principle: 'Limited slots. First come, first served.',
 distLabel: 'City Profit Distribution',
step1: 'Base costs covered first',
step2: 'Profits distributed to partners based on contribution',
distribution: [
  { label: 'City Lead', value: 'Priority' },
  { label: 'Training Partner', value: 'Secondary' },
  { label: 'Community', value: 'Participating' },
  { label: 'Flexible Pool', value: 'As needed' },
],
distNote: 'Specific ratios to be negotiated based on contributions.',
equityLabel: 'Potential Equity',
equityDesc: 'Long-term contributors will have the opportunity to participate in equity, with specific ratios negotiated based on contributions.',
    },
    contact: {
      label: 'Apply',
      title1: 'Apply to become',
      title2: 'a City Partner',
      desc: 'Selected partners will be contacted directly.',
      email: 'business@novara.tech',
      namePlaceholder: 'Your name',
      cityPlaceholder: 'City / Region',
      roleDefault: 'Intended Role',
      emailPlaceholder: 'Your email address',
      subscribeLabel: 'Also subscribe to the early access list for updates and exclusive discounts',
      roles: [
        { value: 'city', label: 'City Partner' },
        { value: 'regional', label: 'Regional Partner' },
        { value: 'community', label: 'Community Participant' },
      ],
      messagePlaceholder: 'Background, resources, and why Novara',
      btnSubmit: 'Apply Now',
      btnSubmitting: 'Submitting...',
      successTitle: 'Application Submitted',
      successDesc: 'Selected partners will be contacted directly.',
      alertMsg: 'Please fill in your name, city, and intended role.',
      errorMsg: 'Something went wrong. Please try again or email us directly.',
      disclaimer: 'Novara operates with a multi-layer capability system, including learning, evaluation, and long-term coordination mechanisms. All partnership structures, profit sharing, and equity incentives will be further negotiated based on specific contributions. Novara reserves the right of final interpretation.',
    },
waitlist: {
  label: 'Early Access',
  title1: 'Subscribe to Early Access List',
  title2: '',
  desc: 'Join as an early follower. Be the first to receive updates and announcements. Early subscribers will receive exclusive course discounts.',
  placeholder: 'Enter your email address',
  btn: 'Subscribe Now',
  btnSubmitting: 'Subscribing...',
  successTitle: 'Subscribed',
  successDesc: 'Welcome to the Novara early access list.',
  errorMsg: 'Subscription failed. Please try again.',
  badge: 'Early Access Benefits',
  invalidEmail: 'Please enter a valid email address',
  perks: [
    { icon: '01', title: 'Latest Updates', desc: 'Be the first to receive latest research and event information' },
    { icon: '02', title: 'Exclusive Discounts', desc: 'Early subscribers receive exclusive course discounts' },
    { icon: '03', title: 'Priority Access', desc: 'Priority participation in Novara events and early access' },
  ],
},

    footer: {
      brand: 'NOVARA',
      tagline: '',
      copy: '© 2026 Novara. All rights reserved.',
    },
  },
}

export default lang